name: Hello Github Actions
on:
  push:
    branches: 
       - main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem no log
        run: echo "Hello, Github Actions!"